#pragma once

#include "ISession.h"
#include <string>
#include <vector>
#include <memory>
#include <optional>

namespace AgentWorkspace {

/**
 * @brief Represents a change or review item generated by an agent.
 */
struct ChangeReviewItem {
    std::string filePath;
    std::string diffSummary;
    bool isApplied;
};

/**
 * @brief The view-model/state for the entire Agent Workspace.
 * This is what the future UI will bind to.
 */
struct WorkspaceState {
    /**
     * @brief All known sessions (active and historical).
     */
    struct SessionListItem {
        std::string id;
        std::string name;
        std::string providerId;
        AgentStatus status;
        std::chrono::system_clock::time_point lastInteraction;
    };
    std::vector<SessionListItem> sessions;

    /**
     * @brief The currently active/selected session.
     */
    std::string selectedSessionId;
    std::shared_ptr<ISession> activeSession;

    /**
     * @brief All available providers.
     */
    std::vector<std::shared_ptr<IAgentProvider>> availableProviders;
    std::string selectedProviderId;

    /**
     * @brief Current working folder state.
     */
    std::string currentWorkingFolder;
    std::vector<std::string> recentWorkingFolders;

    /**
     * @brief Current text in the input composer.
     */
    std::string composerText;

    /**
     * @brief Items pending review (changes proposed by agent).
     */
    std::vector<ChangeReviewItem> pendingReviews;

    /**
     * @brief Overall background task state.
     */
    bool hasActiveBackgroundTasks;
    std::string globalStatusMessage;
};

/**
 * @brief Interface for a manager that coordinates the workspace state.
 */
class IWorkspaceManager {
public:
    virtual ~IWorkspaceManager() = default;

    /**
     * @brief Gets the current state.
     */
    virtual const WorkspaceState& GetState() const = 0;

    /**
     * @brief Actions that can be performed on the workspace.
     */
    virtual void SelectProvider(const std::string& providerId) = 0;
    virtual void SetWorkingFolder(const std::string& folderPath) = 0;
    virtual std::shared_ptr<ISession> CreateSession(const std::string& name) = 0;
    virtual void SelectSession(const std::string& sessionId) = 0;
    virtual void DeleteSession(const std::string& sessionId) = 0;

    virtual void SendPrompt(const std::string& prompt) = 0;
    virtual void CancelActiveOperation() = 0;

    /**
     * @brief UI Binding listener.
     */
    struct IWorkspaceListener {
        virtual ~IWorkspaceListener() = default;
        virtual void OnStateChanged(const WorkspaceState& newState) = 0;
    };
    virtual void AddListener(IWorkspaceListener* listener) = 0;
    virtual void RemoveListener(IWorkspaceListener* listener) = 0;
};

} // namespace AgentWorkspace
